name: rubiks_cube_analyzer
description: Rubik's Cube Analyzer using GAN Smart Cube
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_blue_plus_windows: ^1.14.2
  flutter_web_bluetooth: ^1.0.0
  js: ^0.6.7
  encrypt: ^5.0.3
  lzstring: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/