name: rubiks_cube_analyzer
description: A multi-platform application for analyzing and solving the Rubik's Cube using GAN12 UI Maglev.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5 
  flutter_blue_plus_windows: ^1.26.1
  provider: ^6.1.1
  win32: ^5.2.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/